
BOARD = stm32f3-disco
PROJECT = adc-power-$(BOARD)
BUILD_DIR = bin-$(BOARD)

SHARED_DIR = ../../shared

CFILES = main-$(BOARD).c
CFILES += adc-power.c
CFILES += trace.c trace_stdio.c

VPATH += $(SHARED_DIR)

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

OPENCM3_DIR=../../libopencm3/

### This section can go to an arch shared rules eventually...
LDSCRIPT = $(OPENCM3_DIR)/lib/stm32/f3/stm32f303xc.ld
OPENCM3_LIB = opencm3_stm32f3
OPENCM3_DEFS = -DSTM32F3
FP_FLAGS ?= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS = -mthumb -mcpu=cortex-m4 $(FP_FLAGS)
#OOCD_INTERFACE = stlink-v2
#OOCD_TARGET = stm32f3x
OOCD_FILE = ../../openocd/openocd.stm32f3-disco.cfg

include ../../rules.mk
