BOARD = stm32f072-disco
PROJECT = adc-power-$(BOARD)
BUILD_DIR = bin-$(BOARD)

SHARED_DIR = ../../shared

CFILES = main-$(BOARD).c
CFILES += adc-power.c
# No trace on cm0!
#CFILES += trace.c trace_stdio.c
CFILES += usart_stdio.c

VPATH += $(SHARED_DIR)

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

OPENCM3_DIR=../../libopencm3
DEVICE=stm32f072rb
#OOCD_INTERFACE = stlink-v2
#OOCD_TARGET = stm32f0x
OOCD_FILE = ../../openocd/openocd.stm32f072-disco.cfg

include ../../rules.mk
