
BOARD = stm32f3-disco
PROJECT = adc-power-$(BOARD)
BUILD_DIR = bin-$(BOARD)

SHARED_DIR = ../../shared

CFILES = main-$(BOARD).c
CFILES += adc-power.c
CFILES += trace.c trace_stdio.c

VPATH += $(SHARED_DIR)

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

OPENCM3_DIR=../../libopencm3/
DEVICE=stm32f303vct6
#OOCD_INTERFACE = stlink-v2
#OOCD_TARGET = stm32f3x
OOCD_FILE = ../../openocd/openocd.stm32f3-disco.cfg

include ../../rules.mk
