# This is just a makefile.
# Consider it released into the public domain, or, where not available,
# available under your choice of BSD2clause, MIT, X11, ISC or Apache2 licenses
# Karl Palsson <karlp@tweak.net.au>
BOARD = dut-stm32l073rz
PROJECT = uart-basic-$(BOARD)
BUILD_DIR = bin-$(BOARD)

SHARED_DIR = ../../shared

CFILES = main-$(BOARD).c
CFILES += uart-basic.c

VPATH += $(SHARED_DIR)

INCLUDES += $(patsubst %,-I%, . $(SHARED_DIR))

OPENCM3_DIR=../../libopencm3/

### This section can go to an arch shared rules eventually...
DEVICE=stm32l073rz
#OOCD_INTERFACE = stlink-v2
#OOCD_TARGET = stm32l0x
OOCD_FILE = ../../openocd/openocd.$(BOARD).cfg

include ../../rules.mk
